### ISSUE TITLE
Hi, can you explain it in detail

### ISSUE THREAD

**Issue by hdmjdp** [mmorise/World#125]
https://github.com/mmorise/World/blob/28cbe2bd7a10a8edb1b70aa7a8fa5f2ca70867ed/src/common.cpp#L182

I want to know,  why this function can get the phase of wav from spectrum?

**Comment by mmorise** [comment]
The general channel vocoder generates the vocal cord vibration from the spectrum. Since the spectral envelope has only amplitude information, we must give phase information. In the vocoder, the minimum phase is used as a phase calculated from the power spectrum. It is a reasonable approximation of vocal cord vibration.
