### ISSUE TITLE
Why no allowed_range argument for Harvest?

### ISSUE THREAD

**Issue by fss1t** [mmorise/World#145]
Thank you for looking at my question.

I am trying to analyze the average of  F0 with high accuracy using Harvest.
So I want the F0 estimation errors to disappear as unvoiced.
For that I want to try to adjust allowed_range used in Fix step 1 and Fix step 3 of Harvest.

Is there any reason why Dio has allowed_range argument but Harvest does not?

**Comment by mmorise** [comment]
Harvest has many parameters to obtain an accurate F0 estimation, and all parameters have been optimized using a speech database. Their balance is important, and changing only the allowed_range may decrease the performance.
Because Dio has fewer parameters than Harvest, tuning the allowed_range is not difficult. So, we decided Dio's allowed_range should be controllable.

**Comment by Shogo-Fukawa** [comment]
Thank you for your reply.
I'm convinced.
