### ISSUE TITLE
WORLD Parameters

### ISSUE THREAD

**Issue by Ali20177** [mmorise/World#20]
Hi all,

Could you please tell me how many parameters that WORLD vocoder are used? I know there are three main algorithms were used as DIO, CheapTrick, and PLATINUM. But the missing for me is how many parameters per these algorithms are?

Thanks in advance

**Comment by mmorise** [comment]
Thank you for your contact.

There are not only the controllable parameters but also the fixed parameters.
PLATINUM is not included in the current version. D4C is instead used.
The numbers of controllable parameters in each algorithm are followings
DIO: six parameters
CheapTrick: three parameters
D4C: one parameter
Please see the header files (e.g. dio.h, cheaptrick.h, and d4c.h).
The structs for controlling the parameters are defined.

There are other fixed parameters, but you cannot control them because they are optimized.

Best regards,

**Comment by Ali20177** [comment]
Thank you very much for your reply.
Could you please tell me what are those other fixed parameters? and where I could find them?

Thanks again and regards,

**Comment by mmorise** [comment]
You can find the parameters by seeing .cpp files.
For example, CheapTrick has the parameters such as types of window function (Hanning window) and the length (3/F0). In case that you modified them, you cannot obtain the good result.
All algorithms have such parameters in almost all steps.

So, the best way to know the parameters is to see the source files.

Best regards,

**Comment by Ali20177** [comment]
Thank you again for your feedback ...

Regards,
