### ISSUE TITLE
Make some of the constants changeable at runtime

### ISSUE THREAD

**Issue by giuliopaci** [mmorise/World#3]
I see that there are some constants in constantnumbers.h that someone may want to change at runtime.

For example I have some recordings of a speaker whose F0 sometime goes down to ~40Hz.

Having to change the file in order to be able to change the minimum F0 value is really not convenient.

BTW: line 194 in cheaptrick.cpp;
```
current_f0 = f0[i] <= world::kFloorF0 ? world::kDefaultF0 : f0[i];
```
 correct?

**Comment by mmorise** [comment]
Since world::kFloorF0 is used to determine the fft_size, a discussion whether it can be controlled or not is crucial.
If the user sets the floor to 0, the fft_size will indicate infinity, and it causes a fatal error.
Even if the value is not 0, a huge number of fft_size will be given by the floor.
I think that some restrictions in the floor are needed for safe implementation.
71 Hz is reasonable because of the computational cost (fft_size is fixed to 2048).
Of course, WORLD works even if the floor is lower than 71 Hz.

In the scalability of the program, one modification idea is
1) CheapTrick and D4C have a controllable parameter in f0_floor,
2) The default value is given by world::kDefaultF0 of 71 Hz to fix the fft_size to 2048 sample.
However, if an extremely low value is set by the user, fft_size will be set to a huge value.
2048 sample is not essential, but it is reasonable in almost all speech.
Do you have a good idea to solve this problem?
I think a lower limit is indispensable.

Best regards,

**Comment by giuliopaci** [comment]
This seems to me just an interface issue.
If it was a GUI my suggestion would just be:  make it difficult to the user to make harm to himself (e.g. add a checkbox for confirmation, or something like that).

In this case my suggestion is the same. To make it "difficult", you can just add two min F0 values parameters, one serving the purpose of kFloorF0 and being "more difficult to find for the user that is looking for F0 boundaries limits". It should be clearly marked as "dangerous" in comments and documentation.

Another option to make it "difficult" would be to enforce a limit on FFT size and calcolate kFloorF0. This has the advantage to make it clear to the user the reason why kFloorF0 is present. You should specify effects on F0 and probably the fact that you suggest a power of 2 for this parameter and eventually what will happen if a non-power of 2 is used (e.g. the first power of 2 greater than the provided number is used).

**Comment by giuliopaci** [comment]
In constantnumbers.h:
const double kDefaultF0 = 500.0;

This is why I asked for that line.

**Comment by mmorise** [comment]
In this case, the F0 below f0_floor is dealt with as the consonants.
world::kDefaultF0 is used for analysis/synthesis of consonants.
kDefaultF0 has been determined to improve the sound quality of  plosive consonants based on our previous study.
The duration of plosive consonants is very short. If a lower kDefaultF0 is used,
the sound quality of plosive will deteriorate.

I will modify the program for the users to be able to control the f0_floor in CheapTrick and D4C.
The safeguard is indispensable, and I will write a document and implement a test code.
(I think that there are several cautions for the implementation.)
This modification will be after merging the current pull request.

**Comment by giuliopaci** [comment]
Fine. Thinkin about it a little bit more, I think it would be clearer for users to have a limit on upper bound fft size that they can modify, instead of directly changing f0_floor. This will make them aware of they issue they will face. In the documentation upper bound fft size should reference lower bound F0 limit and viceversa.

In this way, everybody trying to change those parameters will be aware of the issue they will face if they try to force those parameters.

The typical usage scenario I imagine is:
0) default parameters: max_fft_size = 2048, min_F0 = 71;
1) user wants to set a min_F0 to 40, the system reports error and tell that the limit with max_fft_size is 71 and suggest to increase it if one really want min_F0 = 40;
2) user change max_fft_size until either they can use the min_F0 they want or until max_fft_size is too high for them.

**Comment by giuliopaci** [comment]
Regarding line 194 of CheapTrick you confirm that it is correct, right?
```
current_f0 = f0[i] <= world::kFloorF0 ? world::kDefaultF0 : f0[i];
```

or, in other words

```
current_f0 = f0[i] <= 71 ? 500 : f0[i];
```

**Comment by mmorise** [comment]
```
current_f0 = f0[i] <= world::kFloorF0 ? world::kDefaultF0 : f0[i];
```
This code is correct.

> this is because in this case it is assumed we are in a consonant case, right?

Yes, I think that it is a reasonable solution.

Independent assignment of f0_floor and fft_size would cause a confusion because the signal length for windowing is determined by the f0_floor. The window length must be shorter than the fft_size. The mismatch between f0_floor and fft_size should be automatically compensated.

Since I have several ideas, I will modify the code and implement a test script.
However, this task will be conducted in a few days.
(I have another schedule this weekend)

**Comment by giuliopaci** [comment]
No problem. I am not in a hurry and, moreover, I will need some time before I can really test World in a concrete experiment (probably a couple of weeks), when I could need this kind of changes.
Right now I am just grasping the surface from a developer point of view, spotting possible issues that I know I will face if I will end up using this code. :-)

**Comment by mmorise** [comment]
I updated WORLD, and you can control the f0_floor in CheapTrick.
Furthermore, I totally checked the source code and modify them.
In particular, test.cpp was widely modified.
Please note that the argument of Dio() was changed.
(Old version has used the unreasonable argument in option.
New version employed the pointer argument. It is the same as CheapTrick() and D4C().)
