### ISSUE TITLE
DC component

### ISSUE THREAD

**Issue by wuaalb** [mmorise/World#31]
It seems that for voiced frames WORLD synthesis generates a harmonic at DC following the spectral envelope from analysis. Is there perhaps a simple way to avoid this (besides a highpass)? Or was it designed like this on purpose?

It is not really a big deal, but this sometimes causes clipping, affects dynamics compressors, make A/B comparison more difficult, etc.

**Comment by mmorise** [comment]
Sorry, please wait until weekend. I have several deadlines to meet.
I think that the DC component is removed in the synthesis process.
However, if there is a bug, I must check the source code.

I will also check your PR in the weekend.

**Comment by mmorise** [comment]
I checked the program in synthesis.cpp.
The DC component has been generated as you pointed out.
I will implement the process in synthesis() to remove this component.

You may think that the component should be removed in CheapTrick(), but it is difficult because DC component is crucial to estimate the accurate result.
So, the component is removed in synthesis().

**Comment by mmorise** [comment]
I released the new version.
If you found an example that causes a fatal error, please contact me.
I checked this program with only several speech stimuli.

**Comment by wuaalb** [comment]
Thank you very much for the fix!
I've tried the new code only briefly, but so far it looks good to me.

I think that maybe the DC component did help to avoid waveform discontinuities at voiced-unvoiced boundaries; i.e. with the old code the waveform at the end of a voiced region was zero, and with the new code it can be non-zero and decay to zero in the unvoiced region. For example
![harm_only_without_dc_remove](https://cloud.githubusercontent.com/assets/8669162/25307434/f6a94bb8-27a0-11e7-8509-040c83cee0af.png)
![harm_only_with_dc_remove](https://cloud.githubusercontent.com/assets/8669162/25307437/ff6abb24-27a0-11e7-96b8-ce9532da10bd.png)
The top plot is without DC removal, the bottom plot is with DC removal (both without aperiodic component to help visualization).

Anyways, this is just something I noticed, I don't really think it is a problem.

**Comment by r9y9** [comment]
I noticed https://github.com/mmorise/World/commit/00144f85329256bf24124729a0554f76fda95877 produces a bit noisy waveform. Input and generated audio files are attached.

[input_and_generated_audio_files.zip](https://github.com/mmorise/World/files/969528/input_and_generated_audio_files.zip) contains the following files:

- **test16k.wav** the input wav file
- **01test16k_with_00144f8 .wav**: generated wav file with https://github.com/mmorise/World/commit/00144f85329256bf24124729a0554f76fda95877
- **01test16k_without_00144f8 .wav** generated wav file without https://github.com/mmorise/World/commit/00144f85329256bf24124729a0554f76fda95877

I used https://github.com/mmorise/World/blob/4edc2fe63bb5ddb3ec4b719fd55a42bac6f1b0e3/test/test.cpp for testing, so it might be a bug?

**Comment by mmorise** [comment]
The process in DC removal may generate the noise.
In this case, the synthesized speech contains the more DC component compared with the original speech.
The removal process may generate the noise as the unwanted factor.

A safe process for DC removal is required, but it is not easy to instantly develop the appropriate algorithm. Since I have an idea to solve this problem, please give me a time.
I must implement several prototypes to verify the effectiveness of the idea.

**Comment by mmorise** [comment]
I modified the DC removal in synthesis.cpp.
On the other hand, the same processing in synthesisrealtime.cpp has a bug.
Since I could not debug it immediately, I removed this process from the function.

I'll debug it in near future.

**Comment by mmorise** [comment]
I implemented the DC removal in synthesisrealtime.cpp.
Its implementation is different from the implementation in synthesis().
The sound quality is almost all the same in both implementations.

**Comment by r9y9** [comment]
I tried the latest WORLD and I don't see noisy waveform anymore. Thank you very much!
