### ISSUE TITLE
Segmentation fault in cftf1st

### ISSUE THREAD

**Issue by m-toman** [mmorise/World#39]
Hi again,

I'm still integrating the latest WORLD version into a DNN synthesizer (merlin) and now it finally works, sort of. For some samples I get a segmentation fault in fft.cpp, at the expression "wn4r = w[1];"

Here is the input data:
[demo_014.tar.gz](https://github.com/mmorise/World/files/1074411/demo_014.tar.gz)
It's in double format without headers, so "x2x +da" can be used to take a look at it.
I know that the silence part currently has a F0 of 1, which is wrong, but this shouldn't cause the error (also works for most of the other samples).
EDIT: SP is encoded with 60 dimensions, AP with 5

Here is the call stack:
```
cftf1st(int n, int n@entry, double * a, double * a@entry, double * w, double * w@entry) (/home/mtoman/VoiceBuilding-DNN-dev/DNN/merlin/tools/WORLD_v3/src/fft.cpp:1292)
cftfsub(int n, int n@entry, double * a, double * a@entry, int * ip, int * ip@entry, int nw, int nw@entry, double * w, double * w@entry) (/home/mtoman/VoiceBuilding-DNN-dev/DNN/merlin/tools/WORLD_v3/src/fft.cpp:326)
rdft(int n, int n@entry, int isgn, int isgn@entry, double * a, double * a@entry, int * ip, double * w) (/home/mtoman/VoiceBuilding-DNN-dev/DNN/merlin/tools/WORLD_v3/src/fft.cpp:194)
ForwardFFT(fft_plan p) (/home/mtoman/VoiceBuilding-DNN-dev/DNN/merlin/tools/WORLD_v3/src/fft.cpp:52)
fft_execute(fft_plan p) (/home/mtoman/VoiceBuilding-DNN-dev/DNN/merlin/tools/WORLD_v3/src/fft.cpp:145)
GetNoiseSpectrum() (/home/mtoman/VoiceBuilding-DNN-dev/DNN/merlin/tools/WORLD_v3/src/synthesis.cpp:32)
GetAperiodicResponse() (/home/mtoman/VoiceBuilding-DNN-dev/DNN/merlin/tools/WORLD_v3/src/synthesis.cpp:43)
GetOneFrameSegment(double * response, const double * dc_remover, const MinimumPhaseAnalysis * minimum_phase, const InverseRealFFT * inverse_real_fft, const ForwardRealFFT * forward_real_fft, int fs, double current_time, double frame_period, int f0_length, const double * const * aperiodicity, int fft_size, const double * const * spectrogram, int noise_size, double current_vuv) (/home/mtoman/VoiceBuilding-DNN-dev/DNN/merlin/tools/WORLD_v3/src/synthesis.cpp:189)
Synthesis(const double * f0, int f0_length, const double * const * spectrogram, const double * const * aperiodicity, int fft_size, double frame_period, int fs, int y_length, double * y) (/home/mtoman/VoiceBuilding-DNN-dev/DNN/merlin/tools/WORLD_v3/src/synthesis.cpp:340)
main(int argc, char ** argv) (/home/mtoman/VoiceBuilding-DNN-dev/DNN/merlin/tools/WORLD_v3/examples/codec_test/synthraw.cpp:249)
```

Also I am using a slightly modified (hacky) version of the codec_test example to hardcode the header information:
[synthraw.cpp.txt](https://github.com/mmorise/World/files/1074420/synthraw.cpp.txt)
But as it works with other samples, I also think that this hardcoding isn't really an issue.

Do you have any idea? :)
Thanks,
Markus

**Comment by mmorise** [comment]
Thank you for your question.

I go on a business trip until this weekend, so I may not be check it until next Monday.
Since fft.cpp is not my work, it may be difficult for me to debug the program.
I guess that an inappropriate value (e.g. minus value in spectral envelope) is used in synthesis().
(I don't check the program, so it is an idea with no evidence).

**Comment by m-toman** [comment]
Thanks, that's something I can check. 

I ensured that the (coded) ap are below or equal to 0 (they are log, right?) F0s look fine. So I'll test that. If that's it, it's probably worth to add to the Readme.

**Comment by mmorise** [comment]
I found the cause of this problem.
Simply stated, you can overcome this problem by setting the lowest F0 to above 24 Hz.

Buffer overrun was observed in cases where the F0 below 23 Hz was used.
The variable noise_size is used to generate the white noise with length of noise_size.
The generated noise is transformed by FFT with length of fft_size.
In cases where the noise_size is larger than fft_size, buffer overrun occurs.

The noise_size is roughly approximated by fs / F0.
Since the lowest F0 is determied by fs / fft_size (48,000 / 2048 = 23.4), 24 Hz is required to guarantee the safety processing.

I confirmed that the problem was solved by setting the lowest F0 to 24 Hz.
In your data, since the spectrogram in a part of unvoiced section has a large power, the generated waveform has a large noise in these sections.

I consider how to fix this problem.
I think that using a safeguard is reasonable solution.

Best regards,

**Comment by m-toman** [comment]
Thanks, I'll test that ASAP and post the results.

**Comment by m-toman** [comment]
Thank you. So it was the silence part. I set F0 more or less arbitrary because I thought it doesn't matter in unvoiced parts anyway. 
Are you interested in the differences in the synthesis when using codec.cpp instead of MGCs generated by SPTK?

**Comment by mmorise** [comment]
I fixed the bug in the segmentation fault.
The F0 below the threshold is treated as the unvoiced segment.

Since I have never compared my codec with MGCs, I'm interested in the result.
(I believe that the sound quality of the synthesized speech is almost all the same)

**Comment by m-toman** [comment]
I will contact you in the next few days via email once I have some data. 
The issue itself is gone, so I'll close that issue ;). Thanks.
