### ISSUE TITLE
C and MATLAB versions

### ISSUE THREAD

**Issue by maelp** [mmorise/World#40]
Are both versions updated together? The website says that the 2.4.1 is in MATLAB, but it is not clear whether the Github version has been updated

**Comment by mmorise** [comment]
The update is not synchronized in cases where the bug is found in one version.
Functions in the real-time synthesis and codec are provided in C++ version only.
So, it is difficult to synchronize the timing of update in both versions.
However, since the update is synchronized when the calculation result changes, almost the same results are always guaranteed in both versions.
(In random number generation and the processing including round(), it's not always true that the same results are obtained.)

**Comment by maelp** [comment]
Thanks!
