### ISSUE TITLE
phase problem in world matlab

### ISSUE THREAD

**Issue by tuanad121** [mmorise/World#42]
Hi I use the latest world matlab v0.2.1_4 for analysis/synthesis a dataset. It seems the synthesized waveforms is "upside-down" of original waveforms. I think it's because of the phase. I attached an audio file and my matlab scripts down below.
I appreciate any time you can spend for the case.
Thank you 
[world error.zip](https://github.com/mmorise/World/files/1149387/world.error.zip)

**Comment by mmorise** [comment]
As you pointed out, "upside-down" is often observed.
On the other hand, the sound quality is not be affected by this phase.
Since it is difficult to accurately estimate the phase of speech, WORLD uses the minimum phase instead of the phase of speech.

The main cause is the phase at 0 Hz. The synthesis function uses the phase of 0 rad at 0 Hz.
In calculating the minimum phase, we cannot control this value.
If you want to change the phase, you can manually manipulate it after synthesis.

**Comment by tuanad121** [comment]
Thanks for your answer. Now I understand the effect of minimum phase response in WORLD. 
I'm just curious. If I wanna manipulate the phase, can I do this by modifying WORLD parameters (f0, spectra, ap)?
Thank you very much.

**Comment by mmorise** [comment]
Since the phase in each vocal cord vibration is determined by the spectral envelope, we should not manipulate the phase with three parameters.
(You can manipulate the phase by changing the spectral envelope, but the voice timbre also changes.
I think it causes the unwanted result)
All-pass filter is useful to change the phase of the synthesized speech.
