### ISSUE TITLE
Frame size

### ISSUE THREAD

**Issue by ziadah** [mmorise/World#51]
Hi, 
I know that the frame period (step size) is of 5 ms. 
But I cannot find anything related to the frame size used to calculate spectrograms.
Any info would be appreciated.

Thanks !

**Comment by mmorise** [comment]
Spectral envelope estimator has no parameter in the frame period.
The function requires F0 contour and its temporal position.
The temporal position is used as  the parameter in the frame period.

Instead of changing the frame period, you can modify this parameter.
Parameters f0 and temporal_positions must changed synchronously.

Best regards

**Comment by mmorise** [comment]
Sorry, I have misunderstood two words (frame period and frame size).

You cannot change the frame size used to calculate spectrogram and aperiodicity.
The frame size is automatically determined by the F0 information in each frame.
In CheapTrick, the Hanning window with the length of 3 / F0 s is used for windowing.
In D4C, the Hanning and Blackman windows with the length of 4 / F0 s are used.

These algorithms will be able to work in cases where these window functions are used.
If you are interested in the detailed algorithms, please see the references in these algorithms.

**Comment by ziadah** [comment]
Great thank you! you perfectly answered my question.

Sincerely,
