### ISSUE TITLE
build World on MacOS

### ISSUE THREAD

**Issue by weixsong** [mmorise/World#72]
Hi,

Could World be compiled on MacOS? I meet some issue when build on my macbook.

ld -shared, option not supported.

Thanks

**Comment by mmorise** [comment]
> Could World be compiled on MacOS? I meet some issue when build on my macbook.
Yes, we provide a makefile for compile it with any OS.
I think that we cannot use several options in MacOS, and this is not a problem in WORLD.

**Comment by chtertl** [comment]
Hello. I too am trying to get World--specifically, the real time synthesizer--running on MacOS and iOS. It appears to compile and run OK, but so far I haven't got any sound out of it.

A few basic questions:
1. Are there any working examples of code that uses the real time synthesizer?
2. For input to the synthesizer I am coping over corresponding input data from Kyle Kastner's Python adaptation of World. Any reason that would not be expected to work?
3. In particular, numerical values in the python-based mel spectrogram are on the order of 1e-16 to 1e-10. Is this an expected scale for the C++ version?

Thanks for sharing this important toolset.

**Comment by mmorise** [comment]
Thank you for your question.

 In Q1, I know a Swift-based application (https://github.com/Morise-Lab/SOUND_STONE). It is an application for iPad. Since the developer is a Japanese student, the text is in Japanese.

In Q2, I don't know the Kyle Kastner's Python adaptation of World, so I can't answer the question.

In Q3, I think that the order is too small. I tested the code in C++ version, and more large value (around 10) was observed. There may be a bug in your version.

Best regards,

**Comment by weixsong** [comment]
@mmorise , It's my mistake. Yes, it works.
