### ISSUE TITLE
I have some trouble

### ISSUE THREAD

**Issue by Bammuri** [mmorise/World#82]
I clone World and write 'make' commend to build the World.
but there are some trouble. Help me please.
![image](https://user-images.githubusercontent.com/28779618/59155133-5f125600-8abd-11e9-9bb3-31dfa5fbe1e9.png)

**Comment by mmorise** [comment]
What is the OS you used?
Since the OS cannot be identified in the program, the code cannot define the variable DWORD and the function timeGetTime().

To solve this problem, please comment out the lines 29, 32, 49, and 60 if you used an OS except Windows.
If you used Windows, please comment out the lines 23 and 28.
This modification is for test.cpp, so please also modify the ctest.c as well as the test.cpp.
